#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
import subprocess

def main():
    ### DEFINE AND CHECK ARGS
    parser = ArgumentParser(description="Takes a set of ONT-primer prefixes dddRADseq files and a set of barcodes and demultiplexes them.")
    parser.add_argument('-v','--vcf', type=str, required=True)
    parser.add_argument('-p','--prefix', type=str, default='out')
    parser.add_argument('-t','--threads', type=int)
    parser.add_argument('-bi','--bi_snps', type=str, default='true')
    parser.add_argument('-d95','--dp_95ile', type=str)
    parser.add_argument('-md','--min_dp', type=int)
    parser.add_argument('-mq','--min_qual', type=int)
    parser.add_argument('-mgq','--min_gq', type=int)
    parser.add_argument('-mm','--min_maf', type=float)
    parser.add_argument('-mf','--max_fmissing', type=float)
    args = parser.parse_args()
# this will eventually be a python driver script

    command=['main.nf','--vcf',args.vcf]
    subprocess.run(command)

# If this is being imported
if __name__=="__main__":
    main()